import os

SQUARE = 52

BOARD_LEFT, BOARD_TOP = 0, 0
BOARD_WIDTH, BOARD_HEIGHT = SQUARE * 8, SQUARE * 8
STATUS_LEFT, STATUS_TOP = 0, SQUARE * 8
WIN_WIDTH, WIN_HEIGHT = SQUARE * 8, SQUARE * 9

SQUARE_SIZE = (SQUARE, SQUARE)
BOARD_SIZE = (BOARD_WIDTH, BOARD_HEIGHT)
STATUS_WIDTH, STATUS_HEIGHT = 8 * SQUARE, SQUARE
STATUS_OFFSET = (STATUS_LEFT, STATUS_TOP)

BOARD_RECT = (BOARD_LEFT, BOARD_TOP, BOARD_WIDTH, BOARD_HEIGHT)

STATUS_RECT = (STATUS_LEFT, STATUS_TOP, STATUS_WIDTH, STATUS_HEIGHT)
WIN_SIZE = (WIN_HEIGHT, WIN_HEIGHT)
FPS = 30
FONT_SIZE_SMALL = 40
FONT_SIZE_LARGE = 80


KING_BLACK_IMG = os.path.join('assets/', 'king-black.png')
KING_WHITE_IMG = os.path.join('assets/', 'king-white.png')

QUEEN_BLACK_IMG = os.path.join('assets/', 'queen-black.png')
QUEEN_WHITE_IMG = os.path.join('assets/', 'queen-white.png')

ROOK_BLACK_IMG = os.path.join('assets/', 'rook-black.png')
ROOK_WHITE_IMG = os.path.join('assets/', 'rook-white.png')

BISHOP_BLACK_IMG = os.path.join('assets/', 'bishop-black.png')
BISHOP_WHITE_IMG = os.path.join('assets/', 'bishop-white.png')

KNIGHT_BLACK_IMG = os.path.join('assets/', 'knight-black.png')
KNIGHT_WHITE_IMG = os.path.join('assets/', 'knight-white.png')

PAWN_BLACK_IMG = os.path.join('assets/', 'pawn-black.png')
PAWN_WHITE_IMG = os.path.join('assets/', 'pawn-white.png')

WHITE_SQUARE_COLOR = (255, 255, 255)
BLACK_SQUARE_COLOR = (0, 0, 0)

# PAWN PROMOTION MODAL
PROMOTION_MODAL_COLOR = (245, 245, 245)
PROMOTION_MODAL_RECT = (BOARD_LEFT + SQUARE * 2, BOARD_TOP + SQUARE * 2, SQUARE * 4, SQUARE * 4)
PROMOTION_QUEEN_RECT = (PROMOTION_MODAL_RECT[0] + SQUARE, PROMOTION_MODAL_RECT[1] + SQUARE, SQUARE, SQUARE)
PROMOTION_ROOK_RECT = (PROMOTION_MODAL_RECT[0] + 2 * SQUARE, PROMOTION_MODAL_RECT[1] + SQUARE, SQUARE, SQUARE)
PROMOTION_BISHOP_RECT = (PROMOTION_MODAL_RECT[0] + SQUARE, PROMOTION_MODAL_RECT[1] + 2 * SQUARE, SQUARE, SQUARE)
PROMOTION_KNIGHT_RECT = (PROMOTION_MODAL_RECT[0] + 2 * SQUARE, PROMOTION_MODAL_RECT[1] + 2 * SQUARE, SQUARE, SQUARE)

